// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcynjbxjuuzotdwdnicn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjeW5qYnhqdXV6b3Rkd2RuaWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyMTEyMDksImV4cCI6MjA1MDc4NzIwOX0.Zb2CQ5X6iHjiZk4haLiTCAMhXR6-ELpyUyKcpsAUHZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);